# Diz ao Netlify onde está a sua função de backend
[functions]
  directory = "netlify/functions/"

# Diz ao Netlify para instalar as dependências necessárias
[build]
  command = "npm install"
  functions = "netlify/functions"
